- .github/workflows/issue-sync.yaml
This PR adds a parent issue link in the description of synced issues, in the following format:
```
--- Added by trigger ---
Linked issue: <owner>/<repo>#<issue_number>
```
> feat: add parent issue link to created issues

- .github/workflows/issue-sync.yaml
- .github/workflows/milestone-sync.yaml
Adds the [social app template repo](https://github.com/AmplicaLabs/social-app-template/milestones) to the issue & milestone GH sync
> feat: add the social-app-template repo to the issue & milestone sync

- CONTRIBUTING.md
- LICENSE
- README.md
- templates/README.md
- templates/README.template..md
A README template and the application of that template to the Gateway Repository.
Closes: #157 
- Added a template under `./templates`
- Updated README.md
- Added LICENSE and CONTRIBUTING.md files
> New readme and readme template for Gateway projects

- .github/workflows/build.yml
This PR fixes an error with the common build/test CI workflow.
Specifically, the "common" workflow should not have any steps executed, and its failure was causing all other jobs to be skipped.
> fix: common build pipeline errors

- services/content-watcher/libs/common/src/ipfs/ipfs.dsnp.ts
Make sure we encode the `contentHash` field of content announcements as a string instead of a UTF-16 buffer.
> fix: contentHash encoding as string for webhook notification

- README.md
- docs/src/Fundamentals/Architecture.md
- docs/src/Fundamentals/Networks.md
- docs/src/GettingStarted/README.md
Minor updates and suggestions.
> fix: suggestions and typos

- .github/workflows/deploy-gh-pages.yaml
- README.md
- docs/src/BestPractices/README.md
- docs/src/BestPractices/Scalability.md
- docs/src/CHANGELOG.md
- docs/src/CONTRIBUTING.md
- docs/src/Fundamentals/BlockchainBasics.md
- docs/src/Fundamentals/README.md
- docs/src/GettingStarted/README.md
- docs/src/Glossary.md
- docs/src/Integration/BuildingApps.md
- docs/src/Integration/README.md
- docs/src/NextSteps/README.md
- docs/src/NextSteps/Tutorial.md
- docs/src/README.md
- docs/src/Tools/README.md
- services/content-publishing/README.md
- services/content-watcher/README.md
- From #346 comments
- Fixing issues with deployment: https://github.com/ProjectLibertyLabs/gateway/actions/runs/10404141334
> Minor documentation review updates

- .github/workflows/build.yml
- .github/workflows/load-tests.yml
- docs/src/Support/Channels.md
- docs/src/Support/Community.md
The if condition was not working correctly as it was never evaluating to false
Proof of now working (by removing github from the common check):
- https://github.com/ProjectLibertyLabs/gateway/actions/runs/10420903674
- https://github.com/ProjectLibertyLabs/gateway/actions/runs/10420903672
> CI Fix: Run If condition

- package.json
Fixed the issue https://github.com/ProjectLibertyLabs/gateway/actions/runs/10967563235
Related to #492
> fix ci watcher

- docs/src/Run/IPFS.md
Add a working flow for setting up IPFS and concrete information for devs
Closes #596
> add ipfs documentation

- deployment/k8s/frequency-gateway/templates/graph.secret.yaml
- deployment/k8s/frequency-gateway/templates/vault_secrets_hooks.yml
- deployment/k8s/frequency-gateway/values.yaml
Add secret `AT_REST_ENCRYPTION_KEY_SEED`  to graph service configurations
Closes #611
> [k8s] graph at rest encryption key seed

- docs/src/Run/Security.md
>  Gateway Docs Run -> Security Add section about API access

- README.md
Update README documentation for Gateway services.
Expand on on how to get started with Gateway services
and add references to Social App Template.
#603
> chore(README): update gateway readme

- libs/utils/src/decorators/is-signature.decorator.spec.ts
- libs/utils/src/decorators/is-signature.decorator.ts
Related to #615 
- added tests
> signature: added test and fixed bug

- docs/src/Run/Deployment.md
Update deployment.md doc to follow same layout pattern as other docs in this category
> homogenize docs across Run

- developer-docs/account/README.md
Update Account-Service Documentation structure
and content.
> chore(docs): update account service

- developer-docs/graph/README.md
Update Graph Service documentation so that
it reflects the latest changes.
> chore(docs): update graph service

- developer-docs/content-publishing/README.md
Update Content-Publisher-Service Documentation structure
and content.
> chore(docs): update content-publisher

- developer-docs/content-watcher/README.md
Update content watcher docs about docs.
> chore(docs): update content-watcher

- cwagent-configmap-enhanced.yaml
- deployment/k8s/frequency-gateway/templates/account.configmap.yaml
- deployment/k8s/frequency-gateway/templates/cloud-watch.configmap.yaml
- deployment/k8s/frequency-gateway/templates/content.publishing.configmap.yaml
- deployment/k8s/frequency-gateway/templates/content.watcher.configmap.yaml
- deployment/k8s/frequency-gateway/templates/graph.configmap.yaml
- deployment/k8s/frequency-gateway/values.yaml
- docs/src/Run/Monitoring.md
- docs/src/SUMMARY.md
Closes #660 
Adding cloud watch support for any monitoring needs (only tested locally)
> Monitoring Gateway

- .github/workflows/common/set-up-mdbook/action.yaml
> than v0.4.40 has a bug with the sidebar.
> Force mdbook to use v0.4.40

- docs/src/Build/README.md
- docs/src/GettingStarted/SSO.md
Fix Broken links.
- Update links, some files got re-arranged and the links were not updated.
Closes #701
> docs: update links in README and SSO documentation for accuracy

- apps/account-api/test/setup/package-lock.json
- apps/account-api/test/setup/package.json
- apps/content-publishing-worker/src/worker.module.ts
- bash_functions.sh
- docker-compose.yaml
- start.sh
- stop.sh
`content-publishing` module configuration was missing imports, so the worker would not run. There are other miscellaneous bug fixes included.
Corrected miscellaneous bugs.
> fix: minor miscellaneous updates

- .spellcheckerdict.txt
- docs/src/GettingStarted/SSO.md
- docs/src/Troubleshooting.md
- libs/cache/src/cache.config.spec.ts
- tools/ci-k6/main.mjs
- tools/ci-k6/package-lock.json
- tools/ci-k6/package.json
Needed to update some docs
Part of https://github.com/frequency-chain/docs/issues/123
- @wilwade added docs around the SIWF SDK usage
- @mattheworris updated the Troubleshooting docs
> Update docs with information about SIWF SDKs and Troubleshooting

- apps/account-api/src/main.ts
- apps/account-worker/src/main.ts
- apps/account-worker/src/transaction_publisher/publisher.service.ts
- apps/content-publishing-api/src/api.service.ts
- apps/content-publishing-api/src/controllers/v2/asset.controller.v2.ts
- apps/content-publishing-api/src/main.ts
- apps/content-publishing-worker/src/batch_announcer/batch.announcer.service.ts
- apps/content-publishing-worker/src/main.ts
- apps/content-publishing-worker/src/publisher/message.publisher.ts
- apps/content-watcher/src/main.ts
- apps/content-watcher/src/pubsub/pubsub.service.ts
- apps/graph-api/src/api.service.ts
- apps/graph-api/src/main.ts
- apps/graph-worker/src/graph_notifier/graph.monitor.service.ts
- apps/graph-worker/src/main.ts
- libs/blockchain/src/blockchain-rpc-query.service.ts
- libs/blockchain/src/blockchain.service.ts
- libs/blockchain/src/polkadot-api.service.ts
- libs/cache/src/cache-monitor.service.ts
- libs/content-watcher-lib/src/scanner/scanner.service.ts
- libs/openapi/src/openapi.ts
- libs/storage/src/ipfs/ipfs.service.ts
Change how logger.error is called for better stack traces. 
Set up some remaining services to use Pino.
Relates to #477
> Logger cleanup

- libs/blockchain/src/blockchain.service.spec.ts
- libs/blockchain/src/blockchain.service.ts
The goal of this PR is to reduce or eliminate errors due to nonce conflicts.
Closes #974 
There appear to have been two problems:
1. When computing the list of next potentially available nonces, the current nonce was being incremented starting with an index of 0 (ie, `currentNonce + 0 => currentNonce`) instead of 1.
2. When adding the computed offset to the current nonce, 1 was being subtracted (ie, `return currentNonce + offset - 1`, where `offset >= 1`)
Corrected both of these apparent errors.
this seems like it was fundamentally broken; ie, would almost always produce an error. How could it ever have submitted a successful transaction?
It would always error the first time it submitted a transaction; however, as long as retry/next transaction was submitted before the nonce keys expired …
> fix: get next nonce was repeating last-known nonce
