ProjectLibertyLabs/gateway

.gitignore
docker-compose.yaml
environment/env.account-service.template
environment/env.common.template
environment/env.content-publishing-service.template
environment/env.content-watcher-service.template
environment/env.graph-service.template

This PR adds a basic `docker compose` script to bring up all Gateway backend services _excluding_ the Gateway itself (this is for the scenario where the developer has their own Gateway-compatible app, possibly not based on our `social-app-template` repo)
Closes #156

feat: add docker compose script

---

README.md
services/content-publishing/README.md

README links were broken after moving to monorepo
Closes #300

chore: Update README to correct services links; markdown lint fixes

---

services/graph/apps/api/src/api.module.ts
services/graph/apps/worker/src/graph_notifier/graph.monitor.processor.service.ts
services/graph/apps/worker/src/graph_publisher/graph.publisher.processor.service.ts
services/graph/graph-webhooks.openapi.yaml

- Update graph extrinsic monitoring queue to specify a <block-time> backoff
- Increase # of attempts to 10
- Fix bad if check for expiration # of attempts
- Add webhook endpoint specification for graph operation status

[graph] Fix extrinsic tracking

---

.github/workflows/account-release.yml
.github/workflows/content-publishing-release.yml
.github/workflows/content-watcher-release.yml
.github/workflows/graph-release.yml
.github/workflows/release.yml

This PR refactors the release CI pipeline as follows:
- Create `release.yaml` workflow as a common release CI pipeline for all services
- New pipeline uses a matrix approach to release one or all services based on tag prefix
- New pipeline triggers on a "release[publish]" event instead of "push: tag"
- Old individual service release pipelines are set to manual-only for now (will remove in a future PR)

fix: consolidate release CI pipeline to a common workflow

---

.github/workflows/release.yml

Tried to factor out the repo checkout to its own job so that it didn't have to be run multiple times, but that didn't work.

fix: can't exclude repo checkout from matrix

---

services/account/libs/common/src/blockchain/blockchain.service.ts
services/account/libs/common/src/blockchain/create-keys.ts
services/content-publishing/libs/common/src/blockchain/create-keys.ts
services/content-publishing/scripts/local-init.cjs
services/content-watcher/libs/common/src/blockchain/create-keys.ts
services/content-watcher/scripts/chain-setup/local-chain-setup.cjs
services/graph/libs/common/src/blockchain/create-keys.ts

This PR changes our usage of `keyring.addFromUri()` to `keyring.createFromUri()` so that keypairs will not be saved in a long-lived variable.
Note, this is only a minor improvement to security for the following reasons:
1. We do not have control over JS garbage collection, so not way to guarantee that the generated keypair is eliminated from memory at any given point in time
2. The seed phrase used to generate the keypair is currently injected to the application as an environment variable, so anyone with enough access to view the process could also see the environment
Closes #187

fix: use createFromUri instead of addFromUri for keys

---

.github/workflows/release.yml
docker-compose.yaml
services/content-watcher/INSTALLING.md
services/content-watcher/docker-compose.yaml

Rename is happening, so switching the docker hub username with this change.
Closes #322
- Added new secrets to the GitHub org for the new `projectlibertylabs`
- Updated references to docker
1. Do a release
1. No more references to `amplicalabs` Docker

DockerHub username switch `amplicalabs` -> `projectlibertylabs`

---

services/content-publishing/README.md
services/content-publishing/apps/api/src/api.service.ts
services/content-publishing/apps/api/src/metadata.ts
services/content-publishing/apps/worker/src/request_processor/dsnp.announcement.processor.ts
services/content-publishing/libs/common/src/dtos/activity.dto.ts
services/content-publishing/libs/common/src/interfaces/asset-job.interface.ts
services/content-publishing/libs/common/src/interfaces/request-job.interface.ts
services/content-publishing/swagger.json

As a user, I should not have to keep track of the association between an uploaded asset reference ID and its media type. More specifically, I should not be able to tell content-publisher the type of an asset in an Announcment publish request (Broadcast, Reply, etc), as that opens up an attack vector to specify a media type that does not match the actual uploaded asset. content-publisher should be its own source of truth in coordinating asset type with the actual asset.
-  Removed from `AssetDto`, which is included by all of the above
-  Updated using the `generate` scripts 
Closes #338

[bug] content-publisher needs to be its own source of truth for announcement attachments 

---

.github/workflows/release.yml

Fixes the regex used to validate the release tag for the CI pipeline. Was having trouble with a service name containing an embedded hyphen, like `content-publishing` or `content-watcher`.

fix: regex for release tag

---

services/content-watcher/libs/common/src/crawler/crawler.service.ts

When running a local development frequency node, the chain length will be quite short. This results in trying to scan a blocklist that includes negative numbers, which causes the scan to fail and no previous content to be found.
```javascript
// Make sure blockCount is not longer than the current chain length
if (job.data.blockCount >= startBlock) {
job.data.blockCount = startBlock;
}
```
1. Run SAT with a local frequency node and verify that the initial scan completes correctly.

bug: Make sure blockCount is not longer than the current chain length

---

services/content-watcher/libs/common/src/scanner/scanner.service.ts
services/content-watcher/package.json
services/content-watcher/tsconfig.json

This PR fixes the issue where content-watcher does not find new content at the end of the chain as it's posted.
Closes #351

fix: content-watcher scanning end of chain

---

.github/workflows/build.yml
.github/workflows/load-tests.yml
.github/workflows/release.yml
.prettierignore
services/account/apps/api/src/build-openapi.ts
services/account/swagger.json
services/content-publishing/apps/api/src/build-openapi.ts
services/graph/apps/api/src/build-openapi.ts

- GitHub wasn't able to require CI statuses pass for matrixes
- Not everything was being checked
- Docker Hub was hitting 429 api limits
- Common changes were not triggering all the tests

Improve CI

---

services/content-publishing/apps/worker/src/publisher/publishing.service.ts

Resume queue when Capacity is available (was logging event, but not resuming queue)
Closes #392

fix: resume queue in content-publishing when Capacity is available

---

services/account/libs/common/src/blockchain/blockchain.service.spec.ts
services/account/libs/common/src/blockchain/blockchain.service.ts
services/content-publishing/libs/common/src/blockchain/blockchain.service.spec.ts
services/content-publishing/libs/common/src/blockchain/blockchain.service.ts
services/graph/libs/common/src/blockchain/blockchain.service.spec.ts
services/graph/libs/common/src/blockchain/blockchain.service.ts

- Adds logic to startup in `account`, `content-publishing`, `content-watcher` to query the chain for the MSA ID associated with the public key derived from the configured seed phrase; throw an error if it does not match the configured Provider ID
- Syncs initialization code for `BlockchainService` in `graph-service` with the rest of the services' implementations (missed in previous PR)
Closes #419

feat: at startup, check to make sure provider seed phrase matches configured provider ID

---

services/account/apps/api/src/controllers/v1/handles-v1.controller.ts
services/account/apps/api/src/services/handles.service.ts
services/account/libs/common/src/blockchain/blockchain.service.ts
services/account/libs/common/src/types/dtos/handles.request.dto.ts
services/account/swagger.json

We do not have an endpoint to return an encoded payload for signing a change handle call.
Link to GitHub Issue(s): #413 
- Create GET endpoint to return an encoded payload.
- Remove encoding from the POST change handle.
with @JoeCap08055 @enddynayn 
1. Get encoded extrinsic
2. Post change handle

413 changehandle

---

docker-compose.yaml
services/account/apps/api/test/accounts.controller.spec.ts
services/account/apps/api/test/setup/test-sign-ext.ts

We can't build a transaction from an encoded payload and submit the signed transaction to the chain.
I found a few things in this branch that may be useful:
1. There is a `withType` option that should be `true` to include the 0x01 prefix in a signature.
2. Using `addSignature` on a SubmittableExtrinsic does not change the signature that we used from `signAsync`
3. Invalid Transaction: Custom Error 2 is hopefully something not related to the signature.
with @claireolmstead @wilwade

wip: messing with signatures

---

docs/preprocessor.mjs

The preprocessor wasn't replacing all instances on the page.
Fixed it.
1. Pull
1. cd docs
1. mdbook serve
1. See that the two diagrams show up on the main page and the other embeds work

Docs Preprocessor fixes for broken embeds

---

apps/account-api/src/api.module.ts
apps/content-publishing-api/src/api.module.ts
apps/content-publishing-worker/src/batch_announcer/batch.announcer.spec.ts
apps/content-publishing-worker/src/request_processor/dsnp.announcement.processor.spec.ts
apps/content-publishing-worker/src/worker.module.ts
libs/account-lib/src/cache/cache.config.spec.ts
libs/account-lib/src/cache/cache.config.ts
libs/content-publishing-lib/src/cache/cache.config.spec.ts
libs/content-publishing-lib/src/cache/cache.config.ts
libs/content-publishing-lib/src/config/ipfs.config.spec.ts
libs/content-publishing-lib/src/config/ipfs.config.ts
libs/content-publishing-lib/src/queues/queues.module.ts
libs/content-publishing-lib/src/utils/ipfs.client.ts

The recent refactor to configs changed the internal representation of URL config values from string -> JS `URL` object. This caused some problems.
Revert to string representation of URLs.

fix: URLs in configs must be strings, not JS URL objects

---

apps/graph-api/src/main.ts
libs/blockchain/src/blockchain-rpc-query.service.ts
libs/blockchain/src/blockchain.service.ts

closes #606 
- instead of address we needed to pass the keypair.
```
[Nest] 72593  - 10/09/2024, 3:23:29 PM   DEBUG [BlockchainService] claimHandlePayload: {"baseHandle":"macin","expiration":100}
[Nest] 72593  - 10/09/2024, 3:23:29 PM   DEBUG [BlockchainService] accountId: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
[Nest] 72593  - 10/09/2024, 3:23:29 PM   DEBUG [BlockchainService] claimHandleProof: {"Sr25519":"0x907850f0d8f65794571d403641990820e901208170ca805a8916f4d8b4c9102e817385c528c13c39bc87895c28a24ff7a14c6fe9ba971b362873d89a756cb98d"}
[Nest] 72593  - 10/09/2024, 3:23:29 PM   DEBUG [TransactionPublisherService] Submitting tx of size 110, nonce:0, method: handles.claimHandle
[Nest] 72593  - 10/09/2024, 3:23:29 PM   DEBUG [BlockchainService] nextNonce 80
[Nest] 72593  - …
```

bugfix: capacity trx submittion

---

libs/blockchain/src/blockchain-rpc-query.service.ts

closes #500
- Was going to throw error but it didn't help since it would cause the block scanning process to be stuck on that certain block and would not be able to recover. The better option seemed like to only log these cases.

blockchain: event errors

---

bash_functions.sh
start.sh
stop.sh

The goal of this PR is to update the start and stop scripts to use bash_functions.sh imported from Social App Template.   Some of the output has been altered to make the width work out when using special characters.
Closes #456 
1. Do set up required for starting services (e.g. Docker daemon)
1. Uninstall PCRE-grep if you have it (possibly with brew)
1. check out and run the start script, entering default values.
```shell
git co chore/refactor-start-stop-#456
rm .env-saved # optional
./start
```
4. Go through all the questions, make sure there are no problems with the console output, that it's nice and tidy.
5. Verify that the .env-saved file has correct output
6. Then run the stop script and ensure that it does stop the docker containers.
7. Install a PCRE-compatible script and repeat …

update start/stop to use imported bash_functions script

---

Makefile
developer-docs/content-publishing/README.md
developer-docs/content-watcher/README.md

Update Content-Watcher-Service Documentation structure
and content.

chore(docs): update content-watcher docs

---

.github/workflows/release.yml

This PR fixes an issue where the release workflow processes a blank tag when triggered manually instead of from a release event.

fix: make sure correct tag is used when release workflow is triggered manually

---

.github/workflows/release.yml

This PR skips updating the DockerHub image description if the release flow is running as a test run.

fix: do not update DockerHub image description for test runs

---

.github/workflows/e2e-tests.yml
apps/account-api/src/controllers/v1/handles-v1.controller.ts
apps/account-api/src/controllers/v2/accounts-v2.controller.ts
apps/account-api/test/handles.controller.e2e-spec.ts
libs/account-lib/src/utils/blockchain-scanner.service.ts
libs/blockchain/src/blockchain-rpc-query.service.ts

When working with handles, new handles should be validated before sending transactions to the blockchain.
Closes #676 
Implemented `isValidHandle()` which uses `validateHandle()` RPC to validate base handles before sending them to the blockchain.
1. Setup Account Service.
2. Use Swagger to test `/v1/handles/change/{newHandle}` a base handle that is longer than 20 characters and verify that the response is 400.
3. Use example.mjs to use SIWF v2 and choose a handle that is too long and observe the 400 response.

feat: add handle validation using blockchain service in HandlesControllerV1 and AccountsControllerV2

---

docs/css/overrides.css

Some of the headers had odd margins. This corrects them all.

Docs: Fix some heading margins

---

docs/css/overrides.css
scripts/local-init.cjs
tools/siwfv2/example.mjs

Same issue in SIWF, fixed the same way; warning icon overflows and blocks warning text.
Fixes #693 
Add same changes to overrides.css as in that issue.
Run `mdbook serve` after building, and go to http://localhost:3000/GettingStarted/SSO.html to check that the issue is fixed.

Fix warning overflow

---

apps/content-publishing-api/k6-test/helpers.js
apps/content-publishing-api/k6-test/script.k6.js
apps/content-publishing-api/k6-test/script_lg_files.js
apps/content-publishing-api/src/api.service.ts
apps/content-publishing-api/test/mockRequestData.ts
apps/content-publishing-worker/src/batch_announcer/batch.announcer.ts
libs/types/src/dtos/content-publishing/announcement.dto.ts
libs/types/src/interfaces/content-publishing/announcement.interface.ts
libs/utils/src/decorators/is-cidv1.decorator.spec.ts
libs/utils/src/decorators/is-cidv1.decorator.ts
libs/utils/src/decorators/is-dsnp-content-hash.decorator.spec.ts
libs/utils/src/decorators/is-dsnp-content-hash.decorator.ts
tools/ci-k6/main.mjs

- Revert erroneous changes that were made to the DTO validator `@IsDsnpContentHash()` in PR #720
- Add unit tests for validation of spec-supported encoding (base32 only) and hashing algo (sha2-256 or blake3 only) for DSNP content hash
- Add `@IsCidV1()` decorator and unit tests
- Add k6 load tests for recently added endpoints `/v2/content/on-chain` and `v2/content/batchAnnouncement`
Closes #721

fix: revert DSNP content hash validation changes, update tests

---

apps/content-publishing-worker/src/interfaces/batch-announcer.job.interface.ts

Change property name string to reflect property change from `referenceId` to `cid`.
Closes #723

fix: update logic for change in property name

---

apps/content-publishing-api/src/api.service.ts
apps/content-publishing-worker/src/batch_announcer/batch.announcer.ts
libs/storage/src/ipfs/ipfs.service.ts
libs/types/src/constants/queue.constants.ts

This PR does the following:
- overrides the retry limit for pre-existing batchAnnouncement jobs from 1 to 3
- traps failure to retrieve IPFS info of a pinned resource in the batch queue processor and throws an error (prevents erroneous queueing of batch jobs that end up looking like onChain content jobs)
- adds an initial delay of 3s to batchAnnouncement jobs to allow time for asset upload to ipfs

fix: address race condition between asset publishing and batch announcement

---

apps/account-api/src/main.ts

Experienced with Account Service.
Logs from the event:
```
[Nest] 454  - 03/19/2025, 9:54:39 PM    WARN [main] Received shutdown event
[Nest] 454  - 03/19/2025, 9:54:39 PM    WARN [main] app closed
[Nest] 454  - 03/19/2025, 9:54:49 PM     LOG [main] Shutdown timer expired
2025-03-19 21:37:18          API-WS: disconnected from wss://0.rpc.testnet.amplica.io/: 1006:: Abnormal Closure
[Nest] 454  - 03/19/2025, 9:37:18 PM   ERROR [BlockchainRpcQueryService] Communications error with Frequency node; starting 60-second shutdown timer
[Nest] 454  - 03/19/2025, 9:54:39 PM   ERROR [BlockchainRpcQueryService] Failed to reconnect to Frequency node; terminating application
```
Expected: The Container halts
Actual: Container was still running
- Change `process.exit(0)` to `process.exit(1)` when the …

fix: change shutdown timer log level and exit code

---

apps/account-api/src/main.ts
apps/account-worker/src/main.ts
apps/content-publishing-api/src/main.ts
apps/content-publishing-worker/src/main.ts
apps/content-watcher/src/main.ts
apps/graph-api/src/main.ts
apps/graph-worker/src/main.ts
libs/content-publishing-lib/src/utils/blockchain-scanner.service.ts
libs/graph-lib/src/utils/blockchain-scanner.service.ts
libs/logger/logLevel-common-config.ts
libs/storage/src/ipfs/ipfs.service.ts

See #675
This PR enhances log level control by refining how the DEBUG environment variable is used and introducing a new VERBOSE_LOGGING variable for more granular configuration.
Changes
- The `DEBUG=true` environment variable now only enables the debug log level.
- To enable both `debug` and `verbose` log levels, set `DEBUG=verbose`.
- `DEBUG` is defined in the docker-compose.yaml file under the common environment section, enabling debug logging across all gateway services by default.
New Feature
- Introduces the `VERBOSE_LOGGING` environment variable to enable `verbose` logging on a per-service basis.
- It is not defined in the shared `docker-compose.yaml`.
- It must be set in the individual `.env.[service]` file.
- For deployments, it can optionally be added to `docker-compose.yaml` as …

feat: implement dynamic log level configuration across applications

---

apps/account-worker/src/transaction_publisher/publisher.service.ts
apps/content-publishing-worker/src/publisher/message.publisher.ts
apps/content-publishing-worker/src/publisher/publishing.service.ts
apps/graph-worker/src/graph_publisher/graph.publisher.processor.service.ts
libs/blockchain/src/blockchain.service.ts
libs/blockchain/src/types.ts

This PR catches RPC errors on chain extrinsic submission. If the error is due to a nonce conflict, throw a "DelayedError" which will trigger the initiating queue job to go back into the queue for retry (bypassing configured queue retry limits)
Closes #751

feat: allow task retry on nonce conflict error

---

apps/account-api/src/api.config.ts
apps/account-worker/src/transaction_publisher/publisher.service.ts
libs/utils/src/interceptors/interceptors.spec.ts
libs/utils/src/interceptors/timeout.interceptor.ts

This PR adds logging the failed route when a timeout error occurs.
```
[Nest] 43834  - 03/31/2025, 11:06:59 AM   ERROR [GET /sampleRoute] Request took longer than 1000ms to process; throwing timeout error
```
Related issue #768 
Closes #770

feat: log the failed route when a timeout error occurs

---

docs/src/SUMMARY.md

mdbook v0.4.48 fails to parse docs.
Remove duplicate link to `./GettingStarted/QuickStart.md` in `SUMMARY.md`
with @emresurmeli 
Closes #777

fix: remove redundant Quick Start entry from documentation summary

---

libs/cache/src/cache.config.ts

We ran into a problem where the BullMQ "delayed" queue can cause Bull to poll with a delay longer than the default 10s timeout for Redis commands, causing polls to throw "CommandTimeout" errors and delayed jobs to be stuck in the queue. This PR is a hotfix to increase the command timeout temporarily until a more correct solution can be determined.

fix: temporarily bump Redis commandTimeout to 25s

---

apps/content-publishing-worker/src/batch_announcer/batch.announcer.ts
libs/storage/src/ipfs/ipfs.service.spec.ts
libs/storage/src/ipfs/ipfs.service.ts

`ipfs.dag.stat` gives a `size` value that is not the same as the actual size of a file when downloaded.
This is because the DAG stores additional info beyond the raw file bytes.
An example can be seen in the difference between `dag.stat` and `files.stat`, where the actual length of the file is 87,699 bytes:
`dag.stat` reports the incorrect (for our purposes) value (twice, for good measure):
```
% curl -s -d '' '$IPFS_RPC_URL/api/v0/dag/stat?arg=bafybeibkvwtaugltazjt7oeq6xahz2qwvd5sm75twsht3e45niuxnfg654' | jq .
{
"UniqueBlocks": 1,
"TotalSize": 87713,
"Ratio": 1,
"DagStats": [
{
"Cid": "bafybeibkvwtaugltazjt7oeq6xahz2qwvd5sm75twsht3e45niuxnfg654",
"Size": 87713,
"NumBlocks": 1
}
]
}
```
... whereas `files.stat` gives us both the file size and the DAG size:
```
% curl -s -d '' …
```

Announce correct batch file size

---

apps/content-publishing-api/src/api.service.ts

`content-publishing-api` `POST /v2/asset/upload` endpoint has been experiencing unhandled file stream termination errors. Although we have been unable to reproduce locally to determine the root cause, code inspection reveals that we are not handling errors properly on the file streams.
This solution may not eliminate the errors & still result in assets that fail to upload; however, it should at least prevent the application from crashing, and possibly allow for some better data collection as a result.

fix: better file stream error handling

---

apps/content-publishing-worker/src/batch_announcer/batch.announcer.ts
libs/storage/src/ipfs/ipfs.service.spec.ts
libs/storage/src/ipfs/ipfs.service.ts

This PR restores the logic to get the file size of a file in IPFS using the Kubo RPC API, with the added logic to avoid hanging if the file is not cached in the local node.
Closes #832

fix: get correct file size from IPFS, without hanging

---

docker-compose-e2e.account.yaml
docker-compose-published.yaml
docker-compose.yaml

Since `REDIS_URL` and `REDIS_OPTIONS` are now mutually exclusive, make sure any docker compose files do not specify both.

fix: remove REDIS_OPTIONS from docker compose files

---

apps/account-worker/src/main.ts
apps/content-publishing-worker/src/worker.module.ts
apps/content-watcher/src/api.module.ts
apps/content-watcher/src/api.service.ts
apps/content-watcher/src/controllers/v1/scanner.controller.ts
apps/content-watcher/src/controllers/v1/webhooks.controller.ts
apps/content-watcher/src/main.ts
apps/graph-worker/src/main.ts
apps/graph-worker/src/request_processor/request.processor.service.ts
apps/graph-worker/src/worker.module.ts
libs/graph-lib/src/utils/blockchain-scanner.service.spec.ts
libs/graph-lib/src/utils/blockchain-scanner.service.ts
libs/logger/src/logLevel-common-config.ts

Part of #477 , this is the content-watcher portion.
Also, two provider initializations were missing, one in graph-worker and one in content-publisher-worker.
1. run ./start.sh
2. in Docker dashboard, click to see the logs for each of the following and verify that they all start (or can be started) and don't error out due to a failure of the loggers:
- account-api
- account-worker
- content-publishing-api
- content-publishing-worker
- content-watcher   
- graph-api
- graph-worker
You can optionally copy the environment files and set `PRETTY=false` to verify that all of these switch to JSON output.

pino logging for content-watcher. Two remaining provider initializations in modules.

---

Docker/Dockerfile.account
Docker/Dockerfile.content-publishing
Docker/Dockerfile.content-watcher
Docker/Dockerfile.dev
Docker/Dockerfile.graph

`USER gateway` is not enough for k8s and it will still throw:
```
Error: container has runAsNonRoot and image has non-numeric user (gateway), cannot verify user is non-root (pod: "...", container: account-service-api)
```
Switch to `USER 1001` the hard coded user id

Use the user id instead of user name so k8s can pick it up as non-root

---

Docker/Dockerfile.account
Docker/Dockerfile.content-publishing
Docker/Dockerfile.content-watcher
Docker/Dockerfile.dev
Docker/Dockerfile.graph

Unable to run local Gateway containers to test code due to permissions issues.
`npm error code EACCES
npm error syscall mkdir
npm error path /app/node_modules/@0no-co
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/app/node_modules/@0no-co'` 
problem statement, including
Link to GitHub Issue(s): [#887](https://github.com/ProjectLibertyLabs/gateway/issues/887)
Confirm docker user/group command syntax, pre-create node_modules and grant write access to avoid permission issues in docker volumes.
with @shannonwells 
1. ./start.sh with 'n' option for use the published Gateway Services containers.
Removal of existing containers/volumes helped with testing with a clean state, but made the build process rather long.
`docker builder prune -af`
`docker rmi gateway-dev:latest …

fix: adjust docker user creation commands, dev container permissions

---

package-lock.json
package.json

I evidently committed a package.json with `"@polkadot/api": "latest"`, bad me.
Use 16.3.1 like everywhere else.

BUG: don't use latest polkadot-api

---

apps/account-worker/src/transaction_publisher/publisher.service.ts
apps/content-publishing-worker/src/publisher/publishing.service.ts
apps/graph-worker/src/graph_notifier/graph.monitor.service.ts
apps/graph-worker/src/graph_publisher/graph.publisher.processor.service.ts
apps/graph-worker/src/request_processor/request.processor.service.ts

On worker start-up, if there are already queued jobs, it is possible jobs are already processed before dependencies are ready.
e.g.
`ERROR [TransactionPublisherService] Error: Api interfaces needs to be initialized before using, wait for 'isReady'`
Link to GitHub Issue(s): [#780 ](https://github.com/ProjectLibertyLabs/gateway/issues/780)
An existing approach has been to add a blockchain API ready check on worker service bootstrap. I went ahead and added this to all services that depend on the Blockchain Service (and don't already check if the API is ready).

fix: confirm blockchain api is ready on service bootstrap

---

.spellcheckerdict.txt

Recent update to README added "testnet" as a term. Adding it to the spellchecker.

Small fix to recent commit to make spellchecker pass

---

.github/workflows/load-tests.yml

Currently, the CI is having issues meeting load test thresholds. This is variable as we are not sure what kind of CPU & memory allocation CI is running on.
For the time being, instead of arbitrarily lowering thresholds, lets remove this CI job, and research how to make reasonable load tests a part of CI. Will create a related issue.

Remove ultra light CI load test on PRs

---

.gitignore
apps/content-publishing-api/k6-test/script_v2_asset_upload.k6.js
apps/content-publishing-api/src/api.service.ts
libs/logger/src/logLevel-common-config.ts
package-lock.json
package.json
scripts/test/clinic.sh

Part of an investigation into #971  brought about some suggested changes here.
1. This called for a k6 load test against content-publishing's `v2/asset/upload` endpoint.
1. prometheus requests massively pollute logs.
1. finding a memory profiling tool that is a little more diagnostic than prometheus was painful and frustrating, but ultimately got something working.
1. Write a k6 load test against v2 asset upload endpoint
1. Fix the logs
1. Install [clinic](https://clinicjs.org/) and add a simple script that will make clinic use the k6 test for profiling.
In the clinic script, I spent a stupid amount of time trying to convince bash to properly expand a variable and wrap it in single quotes, so one could specify some other k6 script to pass to the `--on-port` parameter on the command line, …

clinic script, k6 script, logging sanitation
